from seleniumbase import SB
import seleniumbase
import time
import os

def tc_01_03():
    with SB(
        extension_dir=os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'temp', 'metamask-chrome'))
        ) as sb:
        sb.sleep(5)
        sb.switch_to_window(1)
        sb.click('input[data-testid="onboarding-terms-checkbox"]')
        sb.click('button:contains("Import an existing wallet")')
        sb.click('#metametrics-opt-in')
        sb.click('button:contains("I agree")')
        sb.type('input[data-testid="import-srp__srp-word-0"]',"noodle")
        sb.type('input[data-testid="import-srp__srp-word-1"]',"shy")
        sb.type('input[data-testid="import-srp__srp-word-2"]',"west")
        sb.type('input[data-testid="import-srp__srp-word-3"]',"loyal")
        sb.type('input[data-testid="import-srp__srp-word-4"]',"stone")
        sb.type('input[data-testid="import-srp__srp-word-5"]',"present")
        sb.type('input[data-testid="import-srp__srp-word-6"]',"asthma")
        sb.type('input[data-testid="import-srp__srp-word-7"]',"target")
        sb.type('input[data-testid="import-srp__srp-word-8"]',"space")
        sb.type('input[data-testid="import-srp__srp-word-9"]',"tattoo")
        sb.type('input[data-testid="import-srp__srp-word-10"]',"disorder")
        sb.type('input[data-testid="import-srp__srp-word-11"]',"desk")
        sb.click('button:contains("Confirm Secret Recovery Phrase")')
        password = "Hieu12344."
        sb.type('input[data-testid="create-password-new"]',password)
        sb.type('input[data-testid="create-password-confirm"]',password)
        sb.click('input[data-testid="create-password-terms"]')
        sb.click('button:contains("Import my wallet")')
        sb.click('button:contains("Got it")')
        sb.click('button:contains("Next")')
        sb.click('button:contains("Done")')
        sb.sleep(5)
        sb.click('button[data-testid="network-display"]')
        sb.click('input[type="checkbox"]')
        sb.click('p:contains("Sepolia")')
        sb.open_new_window()
        sb.open("https://development.arttaca.io/")
        sb.click('button:contains("Connect")')
        sb.click('button:contains("Connect a wallet")')
        sb.click('button:contains("MetaMask")')
        sb.sleep(7)
        sb.switch_to_window(4)
        sb.click('button:contains("Next")')
        sb.click('button:contains("Confirm")')
        sb.switch_to_window(2)
        sb.switch_to_window(3)
        sb.click('button.css-zjr4b9')
        sb.sleep(7)
        sb.switch_to_window(4)
        sb.click('button:contains("Confirm")')
        sb.switch_to_window(3)
        sb.click('button:contains("Create")')
        sb.click('span:contains("Mint a NFT to an Existing Collection")')
        sb.click('span:contains("Select")')
        sb.type('input#name', "autotest0104")
        sb.type('textarea#description', "autotestautotestautotestautotest")
        img_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'img', 'Ed-Sheeran-posing.jpg'))
        sb.choose_file('input[type="file"]', img_path)
        sb.click('span:contains("Mint now")')
        sb.sleep(7)
        sb.switch_to_window(4)
        sb.click('button:contains("Reject")')
        sb.sleep(30)

if __name__ == "__main__":
    tc_01_03()