from seleniumbase import SB
import seleniumbase
import time
import os

def test_01_05():
    with SB(
        extension_dir=os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'temp', 'metamask-chrome'))
        ) as sb:
        url = "https://development.arttaca.io/nft/test0704/1"
        sb.sleep(30)
        sb.switch_to_window(1)
        sb.click('input[data-testid="onboarding-terms-checkbox"]')
        sb.click('button:contains("Import an existing wallet")')
        sb.click('#metametrics-opt-in')
        sb.click('button:contains("I agree")')
        sb.type('input[data-testid="import-srp__srp-word-0"]',"noodle")
        sb.type('input[data-testid="import-srp__srp-word-1"]',"shy")
        sb.type('input[data-testid="import-srp__srp-word-2"]',"west")
        sb.type('input[data-testid="import-srp__srp-word-3"]',"loyal")
        sb.type('input[data-testid="import-srp__srp-word-4"]',"stone")
        sb.type('input[data-testid="import-srp__srp-word-5"]',"present")
        sb.type('input[data-testid="import-srp__srp-word-6"]',"asthma")
        sb.type('input[data-testid="import-srp__srp-word-7"]',"target")
        sb.type('input[data-testid="import-srp__srp-word-8"]',"space")
        sb.type('input[data-testid="import-srp__srp-word-9"]',"tattoo")
        sb.type('input[data-testid="import-srp__srp-word-10"]',"disorder")
        sb.type('input[data-testid="import-srp__srp-word-11"]',"desk")
        sb.click('button:contains("Confirm Secret Recovery Phrase")')
        password = "Hieu12344."
        sb.type('input[data-testid="create-password-new"]',password)
        sb.type('input[data-testid="create-password-confirm"]',password)
        sb.click('input[data-testid="create-password-terms"]')
        sb.click('button:contains("Import my wallet")')
        sb.click('button:contains("Got it")')
        sb.click('button:contains("Next")')
        sb.click('button:contains("Done")')
        sb.open_new_window()
        sb.sleep(30)
        sb.open(url)
        sb.click('button:contains("Connect")')
        sb.click('span:contains("Connect a Wallet")')
        sb.click('button:contains("MetaMask")')
        sb.sleep(30)
        sb.switch_to_window(4)
        sb.click('button:contains("Next")')
        sb.click('button:contains("Confirm")')
        sb.sleep(30)
        sb.switch_to_window(3)
        sb.click('button.css-hnz0pg')
        sb.sleep(30)
        sb.switch_to_window(4)
        sb.click('button:contains("Confirm")')
        sb.sleep(30)
        sb.switch_to_window(3)
        sb.click('button:contains("Buy now")')
        sb.click('span:contains("Checkout with card")')
        sb.sleep(30)
        sb.switch_to_frame('iframe[name="embedded-checkout"]')
        sb.type('input#email',"maianhduong16012004@gmail.com")
        sb.type('input#cardNumber',"4242 4242 4242 4242")
        sb.type('input#cardExpiry',"12/56")
        sb.type('input#cardCvc',"321")
        sb.type('input#billingName',"Mai Anh Duong")

if __name__ == "__main__":
    test_01_05("https://development.arttaca.io/nft/test0704/1")